greenery:

  outputs:
    dbt_noi:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: dbt_noi

    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: prod

    dbt_noi_bigquery:
      type: bigquery
      method: service-account
      project: kinetic-harbor-384413
      dataset: dbt_noi
      threads: 1
      keyfile: /workspaces/data-engineering-bootcamp/00-bootcamp-project/kinetic-harbor-384413-27585638075a_bigquery_and_gcs.json
      location: asia-southeast1

    prod_bigquery:
      type: bigquery
      method: service-account
      project: kinetic-harbor-384413
      dataset: deb_bootcamp
      threads: 1
      keyfile: /workspaces/data-engineering-bootcamp/00-bootcamp-project/kinetic-harbor-384413-27585638075a_bigquery_and_gcs.json
      location: asia-southeast1

  target: dbt_noi_bigquery